### ISSUE TITLE
PyQt files not found by Stdb

### ISSUE THREAD

**Issue by jaredbryan881** [schaefferaj/StDb#18]
I run into an error when trying to import StDb on my institution's cluster (running CentOS 7 with Python 3.7 and Anaconda 4.4.0). I perform the following steps:
```
conda create -n stdb python=3.7 obspy -c conda-forge
conda activate stdb
pip install stdb
import stdb
```
which produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jtbryan/.local/lib/python3.7/site-packages/stdb/__init__.py", line 118, in <module>
    from .gui import EditMsgBox
  File "/home/jtbryan/.local/lib/python3.7/site-packages/stdb/gui.py", line 33, in <module>
    from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QPushButton, QAction, QLineEdit, QMessageBox
ImportError: /home/software/anaconda3/4.4.0/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/jtbryan/.local/lib/python3.7/site-packages/PyQt5/QtWidgets.abi3.so)
```

I think it might be a version issue. I look in `/home/software/anaconda4/4.4.0/lib/` and see only .so files up to PyQt version 5.6.2.

**Comment by paudetseis** [comment]
Thanks Jared! So, StDb installs properly with `pip install`, but then it fails to import? That sounds strange. Can you post the output of `conda list` from within your `stdb` environment?

**Comment by jaredbryan881** [comment]
Here is the output of `conda list`

```
# packages in environment at /home/jtbryan/.conda/envs/stdb:
#
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.4           py37hc58025e_1    conda-forge
chardet                   4.0.0            py37h89c1867_1    conda-forge
cryptography              3.3.1            py37h7f0c10b_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py37h89c1867_3    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.3.1            py37h2527ec5_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
lxml                      4.6.2            py37h77fd288_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
matplotlib-base           3.3.4            py37h0c9df89_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.0           py37haa41c4c_0    conda-forge
obspy                     1.2.2            py37h03ebfcd_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pillow                    8.1.0            py37h4600e1f_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
PyQt5                     5.15.2                    <pip>
pysocks                   1.7.1            py37h89c1867_3    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scipy                     1.6.0            py37h14a347d_0    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.23           py37h5e8e339_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tornado                   6.1              py37h5e8e339_1    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
```

**Comment by paudetseis** [comment]
It looks like your system might be forcing a system-wide path search before looking into the environment. I would check in your .bashrc or whatever "rc" gets loaded and sets your paths.

**Comment by jaredbryan881** [comment]
I uninstalled PyQt5 version 5.15 and ran `conda install -c anaconda pyqt`, which installed pyqt version 5.9.2. This fixed the issue. In  any case, I don't think this issue is related to stdb, so I am closing it. Thank you for your help!
